# Generated by Django 5.0 on 2025-08-20 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_delete_productmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
